name: Qloud Express Release

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@semanticlabsgmbh'
      - run: npm install
        working-directory: qloud-express
      - run: npm publish
        working-directory: qloud-express
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
